language: python
python:
- '3.5'
install:
- pip install flask    --target=packages
script:
- pwd
- ls -la
- mkdir output
- cp -p *.py packages
- cd packages
- zip -r ../output/flask-etf.zip ./
- cd ..
- ls -la output
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJVIDFQIDLODBK5IA
  secret_access_key:
    secure: i6NO46G9DrXP4GPWE7w04GhpZ5NpIbYwiqnMNqmZwQneddelXTvBUjm3ghSkXKzNw7uOIQhqdt+5UMfq3gAcD075kx++mQO3PXZRleNVktJqHHYHjtwBNBEl6NNjeBMo6dLsCex6zED0QkJijn3a8+06iWXeY3pbLqOeQ/TmwYLeeRWGseLcgx7ldef9HWc7ReHY3ZMRGl9PWUxxGIKv4WuQLBjy8elu1EVlKAx/HZhqa1zhwoVHz53wD+ku3yriXJPiqtwJDJlrzy9S81aX53xRAzj4E5RcDl15u5IbSdz+twsZ8FUfoJR+HxeHByu7nQj5LDTCbYpMvapjAvfxA5S0ZFAtSk8fVXQFiGRSkEjDr+kya9zRO5qKbkmPRg9Qir7g77cBSRolihKdEi0RJEO4pJlm+yz08PxH5o3iVplcW9RHyex+KYYrbet4uRAMPqzLynu4PS/yR6k8BT5b9MYZrJ2bZLgxzp0hXGdqEhAF8EPp0UJTYB+mxZ8GALpSKKoybXDLw6sOiyPtFETSxKrgDdsFcvzGkTe4uk/53e/G9eVp8yHP0MTzIoghHx9z0hH4QscNT0fgkFFp2/Gfljo3A41xxF72WMDFKgqf+4YdDm7RtsDseuGCpiiZogS0Qc5dzT03SGzjhWJCbY/pK3Ar3QXG9XWVa4IGPNHLgs0=
  bucket: skynetapps
  local-dir: output
  acl: public_read
  on:
    repo: rjturek/flask-etf
